### ISSUE TITLE
@dataclass and Injecting partially applied functions is no longer supported.

### ISSUE THREAD

**Issue by wooyek** [python-injector/injector#140]
The README suggests a nice patter with `@dataclass`:

```python
@injector.inject
@dataclass
class Website:
    settings: WebsiteSettings
```

But is seems that does not work or I am missing something.

```python
Traceback (most recent call last):
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/injector.py", line 456, in get_binding
    return self._get_binding(key, only_this_binder=is_scope)
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/injector.py", line 451, in _get_binding
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/gunicorn/util.py", line 411, in import_app
    app = app(*args, **kwargs)
  File "/work/wi/wi-original-inventory/src/original_inventory/website/wsgi.py", line 23, in create_app
    return container.get(Website)
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/injector.py", line 707, in get
    binding, binder = self.binder.get_binding(None, key)
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/injector.py", line 465, in get_binding
    binding = self.create_binding(key.interface)
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/injector.py", line 393, in create_binding
    provider = self.provider_for(interface, to)
  File "/data/venvs/wi-original-inventory/lib/python3.6/site-packages/injector.py", line 439, in provider_for
    raise TypeError('Injecting partially applied functions is no longer supported.')
TypeError: Injecting partially applied functions is no longer supported.
```

**Comment by jstasiak** [comment]
Please provide a *full* code sample to reproduce this issue and provide the Injector version you're using. Nothing can be done without those.
